const strTest = "somthingasstrTestformethods"
console.log(strTest.length)
// console.log(strTest.slice(5))
console.log(strTest.substr(17, 21))

// strTest.substr()
// strTest.replace()
// strTest.replaceAll()
// strTest.toUpperCase()
// strTest.toLowerCase()
// strTest.concat()
// strTest.trim()
// strTest.trimStart()
// strTest.trimEnd()
// strTest.padStart()
// strTest.padEnd()
// strTest.charAt()
// strTest.charCodeAt()
// strTest.split()